name: Python Package using Conda

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        use-mamba: true
        miniforge-variant: Mambaforge
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: nlp-proto
        environment-file: environment.yml
    - name: Scrape new LDs
      run: |
        python -B scrape.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4

